Worksheet_1

Problem - 1: Array Creation:

In [ ]:
import numpy as np

# 1. Empty array 2x2
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

# 2. All ones array 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array:\n", ones_array)

# 3. Full array of given shape and value
filled_array = np.full((3, 3), 7, dtype=int)
print("\nFilled Array:\n", filled_array)

# 4. Zeros like given array
original_array = np.array([[5, 6], [7, 8]])
zeros_like_array = np.zeros_like(original_array)
print("\nZeros Like Array:\n", zeros_like_array)

# 5. Ones like given array
ones_like_array = np.ones_like(original_array)
print("\nOnes Like Array:\n", ones_like_array)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nArray from List:\n", array_from_list)


Empty Array:
 [[1.48541132e-315 0.00000000e+000]
 [6.88134534e-310 6.88134535e-310]]

All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
 [[0 0]
 [0 0]]

Ones Like Array:
 [[1 1]
 [1 1]]

Array from List:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
import numpy as np

# 1. Array 10 to 49
arr1 = np.arange(10, 50)
print("Array 10 to 49:\n", arr1)

# 2. 3x3 matrix 0 to 8
arr2 = np.arange(9).reshape((3, 3))
print("\n3x3 Matrix 0 to 8:\n", arr2)

# 3. 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Random array of size 30 and mean
rand_array = np.random.random(30)
mean_val = rand_array.mean()
print("\nRandom Array:\n", rand_array)
print("Mean:", mean_val)

# 5. 10x10 random array, min & max
rand_10x10 = np.random.random((10, 10))
min_val = rand_10x10.min()
max_val = rand_10x10.max()
print("\n10x10 Random Array:\n", rand_10x10)
print("Min:", min_val, "Max:", max_val)

# 6. Zero array of size 10, 5th element 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element 1:\n", zero_array)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with border 1 and inside 0:\n", border_array)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array:
 [0.62786243 0.78668103 0.29046709 0.75895406 0.85550939 0.38861021
 0.90234685 0.29042292 0.29294632 0.62628064 0.67614413 0.70674629
 0.48289764 0.05965094 0.30408987 0.33530808 0.42092006 0.83920876
 0.96745146 0.2430982  0.40684944 0.89426789 0.08972967 0.06995715
 0.76657699 0.74568712 0.69098865 0.03705478 0.97852184 0.02311298]
Mean: 0.5186114290358216

10x10 Random Array:
 [[0.46144207 0.39480117 0.25660534 0.47755114 0.08789203 0.73468476
  0.99438956 0.55812881 0.68070647 0.53269532]
 [0.58953346 0.16109717 0.84949    0.54387575 0.61736544 0.01639827
  0.82001376 0.47551169 0.23066549 0.81889717]
 [0.36281129 0.52815318 0.15239293 0.37167701 0.3172499  0.93459306
  0.16966752 0.8493386  0.48634961 0.7700747 ]
 [0.040

Problem - 3: Array Operations:

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("1. x + y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\n2. x - y:\n", sub_xy)

# 3. Multiply the array with an integer
mul_x = x * 3
print("\n3. x * 3:\n", mul_x)

# 4. Square of each element
square_x = x**2
print("\n4. Square of x:\n", square_x)

# 5a. Dot product of v and w
dot_vw = np.dot(v, w)
print("\n5a. Dot product v . w:", dot_vw)

# 5b. Dot product of x and v
dot_xv = np.dot(x, v)
print("\n5b. Dot product x . v:\n", dot_xv)

# 5c. Dot product of x and y
dot_xy = np.dot(x, y)
print("\n5c. Dot product x . y:\n", dot_xy)

# 6a. Concatenate x and y along rows
concat_xy_row = np.concatenate((x, y), axis=0)
print("\n6a. Concatenate x and y along rows:\n", concat_xy_row)

# 6b. Concatenate v and w along columns
concat_vw_col = np.column_stack((v, w))
print("\n6b. Concatenate v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\n7. Error when concatenating x and v:", e)

# Explanation:
# x has shape (2,2) and v has shape (2,), so np.concatenate fails because
# the number of dimensions along axis=0 do not match.

# Fix by reshaping v to 2D (row vector)
v_reshaped = v.reshape(1, 2)
concat_xv_fixed = np.concatenate((x, v_reshaped), axis=0)
print("\n7. Concatenate x and reshaped v:\n", concat_xv_fixed)


1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. Square of x:
 [[ 1  4]
 [ 9 25]]

5a. Dot product v . w: 219

5b. Dot product x . v:
 [29 77]

5c. Dot product x . y:
 [[19 22]
 [50 58]]

6a. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

6b. Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

7. Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

7. Concatenate x and reshaped v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations:

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)          # inverse of A
I = np.dot(A, A_inv)              # multiply A by its inverse
print("1. A * A^-1 =\n", I)

# Check if it's identity (round to avoid floating point errors)
print("Is approximately Identity:\n", np.allclose(I, np.eye(2)))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB =\n", AB)
print("BA =\n", BA)
print("AB equals BA? ->", np.array_equal(AB, BA))  # should be False

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_TA_T = np.dot(B.T, A.T)
print("\n3. (AB)^T =\n", AB_T)
print("B^T * A^T =\n", B_TA_T)
print("Are they equal? ->", np.allclose(AB_T, B_TA_T))


1. A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is approximately Identity:
 True

2. AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB equals BA? -> False

3. (AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Are they equal? -> True


using Inverse Methods.

In [ ]:
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Using inverse method
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("\nSolution using inverse method: [x, y, z] =", X)

# Using np.linalg.solve
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve: [x, y, z] =", X_solve)


Solution using inverse method: [x, y, z] = [ 2.  1. -2.]
Solution using np.linalg.solve: [x, y, z] = [ 2.  1. -2.]
